::: PyFunceble.cli.continuous_integration.exceptions
